Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SystemWypozyczalniGier.Database;
using SystemWypozyczalniGier.Helpers;
using SystemWypozyczalniGier.Tables;

namespace SystemWypozyczalniGier.Controllers
{
    public class CartController : Controller
    {
        public static readonly float PromoPriceFactor = .7f;
        private readonly DatabaseContext _context;

        public CartController(DatabaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var cart = CartHelper.GetCart(Request);
            var dbGames = _context.Games
                .Where(g => cart.Contains(g.GameId))
                .Include(g => g.Publisher)
                .Include(g => g.Reviews);

            var games = await dbGames.ToListAsync();
            ViewBag.TotalPrice = CalculateCartTotalPrice(games);
            (ViewBag.PromotionedGame, ViewBag.PromotionedGamePrice) = games.Count >= 3 ?
                GetChepestGameAndItsPromotionPrice(games) : (null, 0);

            return View(games);
        }

        public async Task<IActionResult> Payment()
        {
            var cart = CartHelper.GetCart(Request);
            var dbGames = _context.Games
                .Where(g => cart.Contains(g.GameId))
                .Include(g => g.Publisher)
                .Include(g => g.Reviews);

            var games = await dbGames.ToListAsync();
            ViewBag.TotalPrice = CalculateCartTotalPrice(games);

            return View("FakePayment", games);
        }

        public IActionResult RemoveFromCart(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var cart = CartHelper.GetCart(Request);
            cart.Remove((int)id);
            CartHelper.SaveCart(Response, cart);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ConfirmPayment()
        {
            var cart = CartHelper.GetCart(Request);
            var games = _context.Games.Where(g => cart.Contains(g.GameId)).ToList();

            var rentals = games.Select(g => new Rental(UserHelper.LoggedUserEmail, g.GameId, Enumerations.RentalStatus.ACTIVE, DateTime.Now));

            _context.Rentals.AddRange(rentals);
            foreach (var rental in rentals)
            {
                var game = _context.Games.FirstOrDefault(g => g.GameId == rental.GameId)!;
                game.QuantityInStock = Math.Clamp(game.QuantityInStock - 1, 0, game.MaxQuantity);
            }

            await _context.SaveChangesAsync();

            CartHelper.SaveCart(Response, new HashSet<int>());
            return RedirectToAction(nameof(Index));
        }

        public static double CalculateCartTotalPrice(List<Game> games)
        {
            if (games.Count == 0) return 0;

            var (chepestGame, cheapestGamePrice) = GetChepestGameAndItsPromotionPrice(games);
            var totalPrice = games.Aggregate(0.0, (acc, g) =>
                g == chepestGame ? acc + cheapestGamePrice : acc + g.DiscountedPrice);

            return totalPrice;
        }

        public static (Game?, double) GetChepestGameAndItsPromotionPrice(List<Game> games)
        {
            if (games.Count == 0) return (null, 0);

            var game = games.MinBy(g => g.DiscountedPrice)!;
            var price = game.DiscountedPrice * (games.Count >= 3 ? PromoPriceFactor : 1);
            return (game, price);
        }
    }
}

Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SystemWypozyczalniGier.Database;
using SystemWypozyczalniGier.Tables;
using SystemWypozyczalniGier.Enumerations;

namespace SystemWypozyczalniGier.Controllers
{
    public class GamesController : Controller
    {
        private readonly DatabaseContext _context;

        public GamesController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            var databaseContext = _context.Games.Include(g => g.Publisher);
            return View(await databaseContext.ToListAsync());
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "Name", game.PublisherId);
            ViewData["Categories"] = new SelectList(_context.Categories.Where(x => x.GameId == game.GameId), "GameId", "Category");

            return View(game);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "Name");
            var model = new Game
            {
                MainPhotoName = "defaultMainPhotoName",
                Photo1Name = "defaultPhoto1Name"
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Game model, IFormFile mainPhoto, List<IFormFile> thumbnailPhotos, List<Category> categories)
        {
            if (ModelState.IsValid)
            {
                string mainFilePath, mainFileName;
                if (mainPhoto != null && mainPhoto.Length > 0)
                {
                    string guid = Guid.NewGuid().ToString("N");
                    string fileName = $"{guid}_0{Path.GetExtension(mainPhoto.FileName).ToLowerInvariant()}";

                    var rootPath = Path.GetFullPath("wwwroot");
                    var uploadPath = Path.Combine(rootPath, "uploads");
                    var filePath = Path.Combine(uploadPath, fileName);
                    mainFilePath = filePath;
                    mainFileName = fileName;
                }
                else
                {
                    return RedirectToAction(nameof(Create));
                }

                if (thumbnailPhotos != null && thumbnailPhotos.Count > 0)
                {
                    int photoIndex = 1;
                    foreach (var thumbnailPhoto in thumbnailPhotos)
                    {
                        string guid = Guid.NewGuid().ToString("N");
                        string fileName = $"{guid}_{photoIndex}{Path.GetExtension(thumbnailPhoto.FileName).ToLowerInvariant()}";
                        var rootPath = Path.GetFullPath("wwwroot");
                        var uploadPath = Path.Combine(rootPath, "uploads");
                        var filePath = Path.Combine(uploadPath, fileName);

                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            thumbnailPhoto.CopyTo(fileStream);
                            switch (photoIndex)
                            {
                                case 1:
                                    model.Photo1Name = fileName;
                                    break;
                                case 2:
                                    model.Photo2Name = fileName;
                                    break;
                                case 3:
                                    model.Photo3Name = fileName;
                                    break;
                                default:
                                    model.Photo4Name = fileName;
                                    break;
                            }

                        }

                        photoIndex++;
                    }
                    using (var fileStream = new FileStream(mainFilePath, FileMode.Create))
                    {
                        mainPhoto.CopyTo(fileStream);
                        model.MainPhotoName = mainFileName;
                    }
                }
                else
                {
                    return RedirectToAction(nameof(Create));
                }

                _context.Add(model);
                await _context.SaveChangesAsync();

                if (categories != null && categories.Any())
                {
                    foreach (Category category in categories)
                    {
                        var entry = new GameCategory
                        {
                            GameId = model.GameId,
                            Category = category
                        };

                        _context.Add(entry);
                    }
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction(nameof(Create));
        }



        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "Name", game.PublisherId);
            ViewData["Categories"] = new SelectList(_context.Categories.Where(x => x.GameId == game.GameId), "GameId", "Category");

            return View(game);
        }

        // POST: Games/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Game game, [FromForm] IFormFile? mainPhoto, List<IFormFile> thumbnailPhotos, List<Category> categories)
        {
            var existingGame = await _context.Games
                .FirstOrDefaultAsync(g => g.GameId == id);

            if (existingGame == null)
            {
                return NotFound();
            }

            existingGame.PublisherId = game.PublisherId;
            existingGame.Title = game.Title;
            existingGame.Description = game.Description;
            existingGame.Price = game.Price;
            existingGame.Discount = game.Discount;
            existingGame.QuantityInStock = game.QuantityInStock;
            existingGame.MaxQuantity = game.MaxQuantity;
            existingGame.Accessibility = game.Accessibility;
            existingGame.Pegi = game.Pegi;



            if (ModelState.IsValid)
            {
                if (mainPhoto != null && mainPhoto.Length > 0)
                {
                   
                    var rp = Path.GetFullPath("wwwroot");
                    var up = Path.Combine(rp, "uploads");
                    var fp = Path.Combine(up, existingGame.MainPhotoName);

                    if (System.IO.File.Exists(fp))
                    {
                        System.IO.File.Delete(fp);
                    }
                

                    string guid = Guid.NewGuid().ToString("N");
                    string fileName = $"{guid}_0{Path.GetExtension(mainPhoto.FileName).ToLowerInvariant()}";

                    var rootPath = Path.GetFullPath("wwwroot");
                    var uploadPath = Path.Combine(rootPath, "uploads");
                    var filePath = Path.Combine(uploadPath, fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        mainPhoto.CopyTo(fileStream);
                        existingGame.MainPhotoName = fileName;
                    }
                }

                if (thumbnailPhotos != null && thumbnailPhotos.Count > 0)
                {
                    foreach (string? fileName in new[] { existingGame.Photo1Name, existingGame.Photo2Name,
                        existingGame.Photo3Name, existingGame.Photo4Name})
                    {
                        if (!string.IsNullOrEmpty(fileName))
                        {
                            var rootPath = Path.GetFullPath("wwwroot");
                            var uploadPath = Path.Combine(rootPath, "uploads");
                            var filePath = Path.Combine(uploadPath, fileName);
                            if (System.IO.File.Exists(filePath))
                            {
                                System.IO.File.Delete(filePath);
                            }
                        }

                    }
                    existingGame.Photo2Name = null;
                    existingGame.Photo3Name = null;
                    existingGame.Photo4Name = null;
                    int photoIndex = 1;
                    foreach (var thumbnailPhoto in thumbnailPhotos)
                    {
                        string guid = Guid.NewGuid().ToString("N");
                        string fileName = $"{guid}_{photoIndex}{Path.GetExtension(thumbnailPhoto.FileName).ToLowerInvariant()}";
                        var rootPath = Path.GetFullPath("wwwroot");
                        var uploadPath = Path.Combine(rootPath, "uploads");
                        var filePath = Path.Combine(uploadPath, fileName);

                        using (var fileStream = new FileStream(filePath, FileMode.Create))

Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SystemWypozyczalniGier.Database;
using SystemWypozyczalniGier.Enumerations;
using SystemWypozyczalniGier.Helpers;
using SystemWypozyczalniGier.Models;
using SystemWypozyczalniGier.Tables;

namespace SystemWypozyczalniGier.Controllers
{
    public class ShopController : Controller
    {
        private readonly DatabaseContext _context;

        public DatabaseContext Context => _context;

        public ShopController(DatabaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string? title, List<Category> categories)
        {
            var databaseContext = from games in _context.Games
                                  .Include(g => g.Publisher)
                                  select games;

            ViewData["TitleFilter"] = title;
            ViewData["CategoryFilter"] = "";

            if (!string.IsNullOrEmpty(title))
            {
                databaseContext = databaseContext
                    .Where(g => g.Title.Contains(title));
            }

            if (categories.Count > 0)
            {
                foreach (var category in categories)
                {
                    databaseContext = databaseContext
                        .Where(g => g.Categories
                            .Select(c => c.Category)
                            .Contains(category)
                        );

                    ViewData["CategoryFilter"] += $"{category}, ";
                }

                ViewData["CategoryFilter"] = ((string)ViewData["CategoryFilter"])
                    .Trim()
                    .Remove(((string)ViewData["CategoryFilter"]).Length - 2);
            }

            var model = new GameViewModel()
            {
                Games = await databaseContext.ToListAsync(),
                FilterCategories = GameViewModel.AllCategories.Except(categories).ToList() //categories.Count == 0 ? GameViewModel.AllCategories : categories
            };

            return View(model);
        }

        public List<Game> GetGames()
        {
            var query = from game in _context.Games
                        select game;

            return query.ToList();
        }        

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .Include(g => g.Rentals)
                .Include(g => g.Reviews)
                .FirstOrDefaultAsync(m => m.GameId == id);
            if (game == null)
            {
                return NotFound();
            }

            ViewBag.AverageMark = game.Reviews.Count > 0 ?
                (float)game.Reviews.Aggregate(0, (acc, r) => acc + r.Mark) / game.Reviews.Count : 5;
            ViewBag.InCart = Request.Cookies["cart"] != null &&
                (JsonConvert.DeserializeObject<HashSet<int>>(Request.Cookies["cart"]!)?.Contains((int)id) ?? false);

            var activeRental = game.Rentals.FirstOrDefault(r => r.AccountEmail == UserHelper.LoggedUserEmail && r.RentalStatus == Enumerations.RentalStatus.ACTIVE);
            ViewBag.RentalEnd = activeRental != null ? activeRental.RentalTime.AddDays(30).ToString("dd.MM.yyyy") : "";

            return View(game);
        }

        public IActionResult AddToCart(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var cart = CartHelper.GetCart(Request);
            cart.Add((int)id);
            CartHelper.SaveCart(Response, cart);

            return RedirectToAction(nameof(CartController.Index), nameof(CartController).Replace("Controller", ""));
        }

        public IActionResult RemoveFromCart(int? id)
        {
            if (id == null || _context.Games == null)
            {
                return NotFound();
            }

            var cart = CartHelper.GetCart(Request);
            cart.Remove((int)id);
            CartHelper.SaveCart(Response, cart);

            return RedirectToAction(nameof(CartController.Index), nameof(CartController).Replace("Controller", ""));
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SystemWypozyczalniGier</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SystemWypozyczalniGier.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SystemWypozyczalniGier</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@


                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Games"
                                    asp-action="Index">Games</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reviews"
                                    asp-action="Index">Reviews</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rentals"
                                    asp-action="Index">Rentals</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Publishers"
                                    asp-action="Index">Publishers</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="GameCategories"
                                    asp-action="Index">Game Categories</a>
                            </li>
                        }

                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
                            </li>

                        @if (SignInManager.IsSignedIn(User))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                            </li>
                        }

                        @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Accounts"
                        asp-action="Index">Accounts</a>
                        </li> *@
                    </ul>
                    <div class="text-right">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div style="display: flex; align-items: center;">
                                <span>Hello, @UserManager.GetUserName(User)! </span>
                                <form class="form-inline" asp-area="Identity" asp-controller="Account" asp-action="Logout"
                                    asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </div>
                        }
                        else
                        {
                            <a asp-area="Identity" asp-controller="Account" asp-action="Login">Login</a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SystemWypozyczalniGier - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>